theme: jekyll-theme-hacker
baseurl: ""
url: "https://bus42.github.io"
title: "Greg Brewton Github Profile"
description: "GitHub Profile for Greg Brewton"
color_theme: "dark"
header_text: " "
footer_text: " "
